# Generated by Django 5.0.1 on 2024-01-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_profile_location_profile_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
    ]
