# Generated by Django 5.0.1 on 2024-01-24 12:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_remove_about_title_about_about_me"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about_me",
            field=ckeditor.fields.RichTextField(default="No information available"),
        ),
    ]
