# Generated by Django 5.0.1 on 2024-01-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_profile_service_title_alter_profile_about_me"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("icon_url", models.ImageField(upload_to="photos/%Y/%m/")),
                ("description", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="service_title",
        ),
    ]
