# Generated by Django 5.0.1 on 2024-01-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_service_remove_profile_service_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="icon_url",
            field=models.FileField(upload_to="icons/%Y/%m/"),
        ),
    ]
