# Generated by Django 5.0.1 on 2024-01-24 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_alter_service_icon_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
        migrations.AddField(
            model_name="profile",
            name="service_title",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="icon_url",
            field=models.FileField(upload_to="photos/%Y/%m/"),
        ),
    ]
