# Generated by Django 5.0.1 on 2024-01-24 18:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_delete_about_profile_service_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testimonial_title", models.CharField(max_length=255)),
                ("testimonial_avi", models.FileField(upload_to="photos/%Y/%m/")),
                (
                    "testimonials_text",
                    ckeditor.fields.RichTextField(
                        default="say something about your self here"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=ckeditor.fields.RichTextField(
                default="say something about your self here"
            ),
        ),
    ]
