# Generated by Django 5.0.1 on 2024-01-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0011_profile_created_service_created_testimonial_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_logo", models.ImageField(upload_to="photos/%Y/%m/")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
