# Generated by Django 5.0.1 on 2024-01-26 17:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0013_client_client_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=255)),
                ("timeline", models.CharField(max_length=255)),
                (
                    "Summary",
                    ckeditor.fields.RichTextField(
                        default="say something about your education"
                    ),
                ),
            ],
        ),
    ]
