# Generated by Django 5.0.1 on 2024-01-26 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0014_education"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="qualification",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
