# Generated by Django 5.0.1 on 2024-01-27 02:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0015_education_qualification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="Summary",
            new_name="summary",
        ),
    ]
