# Generated by Django 5.0.1 on 2024-01-27 02:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0016_rename_summary_education_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organisation_name", models.CharField(max_length=255)),
                ("timeline", models.CharField(max_length=255)),
                ("postion", models.CharField(max_length=255)),
                (
                    "summary",
                    ckeditor.fields.RichTextField(
                        default="say something about your education"
                    ),
                ),
            ],
        ),
    ]
