# Generated by Django 5.0.1 on 2024-01-27 03:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0017_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_title", models.CharField(max_length=255)),
                (
                    "skill_summary",
                    ckeditor.fields.RichTextField(
                        default="say something about your skill"
                    ),
                ),
            ],
        ),
    ]
