# Generated by Django 5.0.1 on 2024-01-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0018_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Web development", "Web development"),
                            ("App development", "App development"),
                            ("Wordpress", "Wordpress"),
                            ("Office 365 setup", "Office 365 setup"),
                        ],
                        max_length=255,
                    ),
                ),
                ("photo", models.ImageField(upload_to="photos/%Y/%m/")),
                ("summary", models.CharField(max_length=255)),
            ],
        ),
    ]
