# Generated by Django 5.0.1 on 2024-01-28 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0019_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AI", "AI"),
                            ("App development", "App development"),
                            ("Wordpress", "Wordpress"),
                            ("Office 365 setup", "Office 365 setup"),
                        ],
                        max_length=255,
                    ),
                ),
                ("photo", models.ImageField(upload_to="photos/%Y/%m/")),
                (
                    "datetime",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("summary", models.CharField(max_length=255)),
            ],
        ),
    ]
