# Generated by Django 5.0.1 on 2024-01-29 00:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0021_post_delete_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pub_photo",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="photos/%Y/%m/"
            ),
            preserve_default=False,
        ),
    ]
