# Generated by Django 5.0.1 on 2024-02-03 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0026_certificate_external_link_alter_certificate_issuer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="category",
        ),
    ]
