# Generated by Django 5.0.1 on 2024-02-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0030_alter_certificate_issue_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
