# Generated by Django 5.0.1 on 2024-02-04 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0031_project_project_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="external_link",
            field=models.URLField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
