# Generated by Django 5.0.1 on 2024-02-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0032_alter_certificate_external_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="external_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
