# Generated by Django 5.0.1 on 2024-02-04 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0033_alter_certificate_external_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_url",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
