# Generated by Django 5.0.1 on 2024-02-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0034_client_client_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
