# Generated by Django 5.0.1 on 2024-02-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0036_education_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
